config/routes.rb
# Copyright (c) 2025 Structural Line Incorporated
# SPDX-License-Identifier: GPL-2.0-or-later
# https://sl-inc.co.jp

# ルーティング情報を記載するファイル
# このファイルの変更時はRedmineを再起動する必要あり

RedmineApp::Application.routes.draw do
  # 選択されたプロジェクトのガントチャート閲覧画面
  get 'projects/:project_id/detailed_schedule_gantt', 
    to: 'detailed_schedule_gantt#show'
  
  # 全てのプロジェクト表示したガントチャートの閲覧画面
  get 'detailed_schedule_gantt/show_all_projects',
    to: 'detailed_schedule_gantt#show_all_projects'

  # Handsontableの行単位でチケットを更新するAPI
  post 'projects/:project_id/detailed_schedule_gantt/bulk_update_issue',
    to: 'detailed_schedule_gantt#bulk_update_issue'

  # Handsontableの行単位でプロジェクトを更新するAPI
  post 'projects/:project_id/detailed_schedule_gantt/bulk_update_project',
    to: 'detailed_schedule_gantt#bulk_update_project'

  # Handsontableで選択した行（チケット）を削除するAPI 
  delete 'projects/:project_id/detailed_schedule_gantt/delete_selected_issues',
    to: 'detailed_schedule_gantt#delete_selected_issues'
   
  # Handsontableで選択した行（チケット）をコピーするAPI
  post 'projects/:project_id/detailed_schedule_gantt/copy_issues',
    to: 'detailed_schedule_gantt#copy_issues'

  # Handsontableで空のチケットを作成するAPI
  post 'projects/:project_id/detailed_schedule_gantt/create_empty_issues',
    to: 'detailed_schedule_gantt#create_empty_issues'

  # Handsontableを最新のデータに更新するためのAPI
  get 'projects/:project_id/detailed_schedule_gantt/get_data',
    to: 'detailed_schedule_gantt#get_data'

  # Handsontableを最新のデータに更新するためのAPI（全プロジェクト対応）
  get 'detailed_schedule_gantt/get_data_all_projects',
    to: 'detailed_schedule_gantt#get_data_all_projects'
  
  # Handsontableの最終更新日時を取得するAPI
  get 'projects/:project_id/detailed_schedule_gantt/get_latest_update',
    to: 'detailed_schedule_gantt#get_latest_update'
  
  # Handsontableの最終更新日時を取得するAPI。プロジェクトを指定しない時に使う
  get 'detailed_schedule_gantt/get_latest_update',
    to: 'detailed_schedule_gantt#get_latest_update'

  # プロジェクト管理行の開始日と期日を更新するAPI
  post 'projects/:project_id/detailed_schedule_gantt/update_project_date',
    to: 'detailed_schedule_gantt#update_project_date'

  # マイルストーン行の開始日と期日を更新するAPI
  post 'projects/:project_id/detailed_schedule_gantt/update_version_date',
    to: 'detailed_schedule_gantt#update_version_date'

  # ソートナンバーを更新するAPI
  post 'projects/:project_id/detailed_schedule_gantt/update_sort_number',
    to: 'detailed_schedule_gantt#update_sort_number'

  # 行の色を更新するAPI
  post 'projects/:project_id/detailed_schedule_gantt/change_row_color',
    to: 'detailed_schedule_gantt#change_row_color'
end

app/models/gantt_latest_update.rb
# Copyright (c) 2025 Structural Line Incorporated
# SPDX-License-Identifier: GPL-2.0-or-later
# https://sl-inc.co.jp

# スプレッドシートの最終更新日時を管理するテーブル
class GanttLatestUpdate < ApplicationRecord
  self.table_name = 'gantt_latest_updates'

  # ---- Associations ----
  belongs_to :project, optional: true, inverse_of: nil

  # ---- Validations ----
  validates :project_id, uniqueness: true, allow_nil: true
  validates :last_update_date, presence: true
  validates :last_update_user_id, presence: true

  # ---- Scopes ----
  scope :for_project, ->(project_id) {
    if project_id.nil?
      where(project_id: nil)
    else
      where(project_id: project_id)
    end
  }

  # ---- API（軽量ユーティリティ）----
  # プロジェクトの最終更新時刻を現在時刻で更新（レコードがなければ作成）
  def self.touch_for(project_id, user_id:, at: Time.current)
    record = find_or_initialize_by(project_id: project_id)
    record.last_update_date = at
    record.last_update_user_id = user_id
    record.save!
  end

  # 取得ヘルパ : 最終更新日時とそのユーザーIDを返す
  def self.last_for(project_id)
    last_update_date, last_update_user_id = for_project(project_id).pick(:last_update_date, :last_update_user_id)
  { last_update_date: last_update_date, last_update_user_id: last_update_user_id }
  end
end

app/models/issue_daily_schedule.rb
# Copyright (c) 2025 Structural Line Incorporated
# SPDX-License-Identifier: GPL-2.0-or-later
# https://sl-inc.co.jp

class IssueDailySchedule < ApplicationRecord
  self.table_name = 'issue_daily_schedules'

  # ---- Associations ----
  belongs_to :issue, inverse_of: :issue_daily_schedules

  # ---- Validations ----
  validates :schedule_date, presence: true,
                            uniqueness: { scope: :issue_id }

  # precision: 5, scale: 2 なので上限は 999.99
  MAX_MAN_DAYS = 999.99
  validates :man_days,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: MAX_MAN_DAYS
            },
            allow_nil: true

  # DBのdefault(0)があるが、nilで渡された場合に備えて丸めも実施
  before_validation :normalize_man_days

  # 1日の合計工数も更新する
  after_save :update_user_daily_schedule
  after_destroy :update_user_daily_schedule


  private

  def normalize_man_days
    # 空文字を nil に変換
    if man_days.is_a?(String)
      if man_days.strip.empty?
        self.man_days = nil
      end
    end

    # nil の場合はここで処理を終える
    if man_days.nil?
      return
    end

    # 数値変換と丸め処理
    self.man_days = man_days.to_d.round(2)

    if man_days.negative?
      self.man_days = 0
    elsif man_days > MAX_MAN_DAYS
      self.man_days = MAX_MAN_DAYS
    end
  end

  # 1日の合計工数を更新する
  def update_user_daily_schedule
    # issueと担当者と日付のどれかがなければ returnする
    unless issue&.assigned_to_id && schedule_date
      return
    end 

    user_id = issue.assigned_to_id
    date    = schedule_date

    # 更新があった日付の対象ユーザーの工数を合計する
    total = IssueDailySchedule
              .joins(:issue)
              .where(schedule_date: date, issues: { assigned_to_id: user_id })
              .sum(:man_days)

    #  合計工数を更新または作成
    uds = UserDailySchedule.find_or_initialize_by(user_id: user_id, schedule_date: date)
    uds.total_man_days = total
    uds.save!
  end
end

app/models/issue_sort_order.rb
# Copyright (c) 2025 Structural Line Incorporated
# SPDX-License-Identifier: GPL-2.0-or-later
# https://sl-inc.co.jp

# app/models/issue_sort_order.rb
class IssueSortOrder < ApplicationRecord
  belongs_to :user
  belongs_to :issue

  validates :user_id, :issue_id, :sort_number, presence: true
end

app/models/user_daily_schedule.rb
# Copyright (c) 2025 Structural Line Incorporated
# SPDX-License-Identifier: GPL-2.0-or-later
# https://sl-inc.co.jp
#
# ユーザーごとの日次合計工数を保持するモデル。
# 各 (user_id, schedule_date) は一意であり、各ユーザー毎に1日の工数合計を表す。
#
class UserDailySchedule < ApplicationRecord
  # ---- Associations ----
  belongs_to :user

  # ---- Validations ----
  before_validation :round_total_to_2dp
  validates :user_id, presence: true
  validates :schedule_date, presence: true, uniqueness: { scope: :user_id }
  validates :total_man_days,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 999.99
            }

  private

  def round_total_to_2dp
    # nil → 0
    self.total_man_days = 0 if total_man_days.nil?

    # BigDecimal に変換して小数第2位に丸め
    self.total_man_days = total_man_days.to_d.round(2)

    # 負の値 → 0
    self.total_man_days = 0 if total_man_days.negative?

    # 上限値超過 → 999.99
    self.total_man_days = 999.99 if total_man_days > 999.99
  end
end

app/helpers/redmine_detailed_schedule_gantt/issue_extra_helper.rb
# Copyright (c) 2025 Structural Line Incorporated
# SPDX-License-Identifier: GPL-2.0-or-later
# https://sl-inc.co.jp

module RedmineDetailedScheduleGantt
  module IssueExtraHelper
    # "1.5 日" のように表示（空は "-"）
    # ただし 0 のときは "0 日"
    def gantt_format_days(value)
      return '-' if value.blank?

      v = begin
        Float(value)
      rescue
        nil
      end
      return '-' if v.nil?

      if v.zero?
        "0 #{l(:label_day)}"
      else
        "#{format('%.2f', v)} #{l(:label_day)}"
      end
    end
  end
end

app/views/detailed_schedule_gantt/_form.html.erb
<!-- 
  Copyright (c) 2025 Structural Line Incorporated
  SPDX-License-Identifier: GPL-2.0-or-later
  https://sl-inc.co.jp
-->

<%# フィルタ、オプション、表示する年月、カスタムクエリ を設定するフォーム%>

<%# プロジェクトIDが取得できなければ全てのプロジェクトを表示する %>
<% action_name = @project.present? ? 'show' : 'show_all_projects' %>

<% base = { controller: 'detailed_schedule_gantt', action: action_name } %>
<% base[:project_id] = @project if @project.present? %>

<% url_opts = base.merge(
      month:  params[:month],
      year:   params[:year],
      months: params[:months]
    ) %>

<%= form_tag(url_opts, method: :get, id: 'query_form') do %>
  <%= hidden_field_tag 'set_filter', '1' %>

  <%# フィルタ %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <div id="query_form_content">
      <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
        <legend onclick="toggleFieldset(this);" class="icon icon-<%= @query.new_record? ? "expanded" : "collapsed" %>">
          <%= sprite_icon(@query.new_record? ? "angle-down" : "angle-right", rtl: !@query.new_record?) %>
          <%= l(:label_filter_plural) %>
        </legend>
        <div style="<%= @query.new_record? ? "" : "display: none;" %>">
          <%= render partial: 'queries/filters', locals: { query: @query } %>
        </div>
      </fieldset>

      <%# オプション %>
      <fieldset id="options" class="collapsible collapsed">
        <legend onclick="toggleFieldset(this);" class="icon icon-collapsed">
          <%= sprite_icon("angle-right", rtl: true) %>
          <%= l(:label_options) %>
        </legend>
        <div style="display: none;">
          <div>
            <fieldset>
              <legend><%= l(:field_column_names) %></legend>
              <div id="list-definition">
                <div>
                  <label for="draw_selected_columns">
                    <%= check_box 'query', 'draw_selected_columns', id: 'draw_selected_columns', 'data-enables' => '#list-definition .query-columns select, #list-definition .query-columns input' %>
                    <%= l(:label_display) %>
                  </label>
                </div>
                <div>
                  <%= render_query_columns_selection(@query) %>
                </div>
              </div>
            </fieldset>
            <fieldset>
              <legend><%= l(:label_related_issues) %></legend>
              <label for="draw_relations">
                <%= check_box 'query', 'draw_relations', id: 'draw_relations' %>
                <% [IssueRelation::TYPE_BLOCKS, IssueRelation::TYPE_PRECEDES].each do |rel| %>
                  <% color = Redmine::Helpers::Gantt::DRAW_TYPES[rel][:color] %>
                  <%= content_tag(:span, '&nbsp;&nbsp;&nbsp;'.html_safe, style: "background-color: #{color}") %>
                  <%= l(IssueRelation::TYPES[rel][:name]) %>
                <% end %>
              </label>
            </fieldset>
            <fieldset>
              <legend><%= l(:label_gantt_progress_line) %></legend>
              <label for="draw_progress_line">
                <%= check_box 'query', 'draw_progress_line', id: 'draw_progress_line' %>
                <%= l(:label_display) %>
              </label>
            </fieldset>
          </div>
        </div>
      </fieldset>
    </div>

    <%# 1か月進む または、戻るボタン %>
    <p class="contextual">
      <span>
        <%= link_to_previous_month(@gantt.year_from, @gantt.month_from, accesskey: accesskey(:previous), onclick: "if (window.editModeManager && !window.editModeManager.getIsEditMode()) { window.onbeforeunload = null; } return true;") %> |
        <%= link_to_next_month(@gantt.year_from, @gantt.month_from, accesskey: accesskey(:next), onclick: "if (window.editModeManager && !window.editModeManager.getIsEditMode()) { window.onbeforeunload = null; } return true;") %>
      </span>
    </p>

    <%# このスプレッドシートに戻ってくるためのアクションを定義 %>
    <% project_ref = @project&.identifier || @project&.id %>
    <% back_to_spreadsheet = 
			if project_ref.present?
				url_for(
					controller: 'detailed_schedule_gantt',
					action: 'show',
					project_id: @project,
					spreadsheet: 1,     
					only_path: true 
      	) 
			else
				url_for(
					controller: 'detailed_schedule_gantt',
					action: 'show_all_projects',
					spreadsheet: 1,     
					only_path: true 
      	) 
			end
		%>

    <p class="buttons">
      <%= number_field_tag 'months', @gantt.months, min: 1, max: Setting.gantt_months_limit.to_i, autocomplete: false %>
      <%= l(:label_months_from) %>
      <%= select_month(@gantt.month_from, prefix: "month", discard_type: true) %>
      <%= select_year(@gantt.year_from, prefix: "year", discard_type: true) %>

      <%# クリアボタン %>
      <%= button_tag type: 'submit', class: 'icon icon-checked' do %>
        <%= sprite_icon('checked', l(:button_apply)) %>
      <% end %>

      <%# クリアボタン %>
      <%= link_to sprite_icon('reload', l(:button_clear)), { project_id: @project, set_filter: 1 }, class: 'icon icon-reload' %>

      <%# カスタムクエリを保存ボタン %>
      <% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, global: true) %>
        <%= link_to(
          sprite_icon('save', l(:button_save_object, object_name: l(:label_query)).capitalize),
          (@project ?
            new_project_query_path(@project, back_url: back_to_spreadsheet) :
            new_query_path(back_url: back_to_spreadsheet)),
          class: 'icon icon-save button'
        ) %>
      <% end %>

      <% if !@query.new_record? && @query.editable_by?(User.current) %>
        <%# カスタムクエリを編集ボタン %>
        <%= link_to sprite_icon('edit', l(:button_edit_object, object_name: l(:label_query)).capitalize),
                    edit_query_path(@query, back_url: back_to_spreadsheet),
                    class: 'icon icon-edit' %>

        <%# カスタムクエリを削除ボタン %>
        <%= delete_link(
          query_path(@query, back_url: back_to_spreadsheet),
          {},
          l(:button_delete_object, object_name: l(:label_query)).capitalize
        ) %>
      <% end %>

      <!-- エディットモード切替ボタン -->
      <%# プロジェクトを選択していればボタンを表示、していなければ読み取り専用 %>
      <span class="editmode-with-indicator">
        <% if @project %>
          <button id="toggle-edit-mode" type="button">
            <span id="edit-mode-status">編集モード</span>
          </button>
        <% else %>
          <span class="read-only-btn">
            <span>読み取り専用</span>
          </span>
        <% end %>

        <span id="loading-indicator">
          <span class="spinner"></span>
          <span>読み込み中...</span>
        </span>
      </span>
    </p>
  </div>
<% end %>

app/views/detailed_schedule_gantt/_header_assets.html.erb
<!-- 
  Copyright (c) 2025 Structural Line Incorporated
  SPDX-License-Identifier: GPL-2.0-or-later
  https://sl-inc.co.jp
-->

<%# HandsontableのCSSを読み込む %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/handsontable@14.4.0/dist/handsontable.full.min.css">
<%# HandsontableのJSを読み込む %>
<script src="https://cdn.jsdelivr.net/npm/handsontable@14.4.0/dist/handsontable.full.min.js"></script>
<%# プラグインのCSSを読み込む %>
<%= stylesheet_link_tag 'detailed_schedule_gantt', plugin: 'redmine_detailed_schedule_gantt' %>
<!-- スプレッドシート用アセット（常時読込） -->
<%= javascript_include_tag 'factory',                     plugin: 'redmine_detailed_schedule_gantt' %>

<%= javascript_include_tag 'create_gantt_spreadsheet/column_configurator',      plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'create_gantt_spreadsheet/column_widths_manager',    plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'create_gantt_spreadsheet/create_handsontable',       plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'create_gantt_spreadsheet/header_generator',         plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'create_gantt_spreadsheet/milestone_rows_generator',        plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'create_gantt_spreadsheet/project_control_rows_generator',        plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'create_gantt_spreadsheet/user_total_days_generator',        plugin: 'redmine_detailed_schedule_gantt' %>

<%= javascript_include_tag 'add_setting/cell_properties',        plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/drag_handler',        plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/edit_mode_manager',        plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/issues_save_handler',        plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/projects_save_handler',        plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/sort_number_updater',        plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/visuable_manager',        plugin: 'redmine_detailed_schedule_gantt' %>

<%= javascript_include_tag 'add_setting/edit/change_row_color',            plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/edit/paste_handler',            plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/edit/row_deleter',              plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/edit/row_inserter',             plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/edit/row_copier',            plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'add_setting/edit/undo_handler',            plugin: 'redmine_detailed_schedule_gantt' %>


<%= javascript_include_tag 'util/clipboard_checker',        plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'util/constants',                plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'util/data_transformer',         plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'util/day_keys_generator',       plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'util/holiday_checker',          plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'util/reload_manager',       plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'util/send_request',       plugin: 'redmine_detailed_schedule_gantt' %>
<%= javascript_include_tag 'util/today_checker',            plugin: 'redmine_detailed_schedule_gantt' %>

app/views/detailed_schedule_gantt/_issue_extra_details.html.erb
<%#
  Copyright (c) 2025 Structural Line Incorporated
  SPDX-License-Identifier: GPL-2.0-or-later
  https://sl-inc.co.jp
%>

<%# 見積工数と予定済工数を表示するフィールドを追加 %>

<% issue = local_assigns[:issue] || @issue %>

<div id="detailed-schedule-gantt-extra-attributes">
  <%= issue_fields_rows do |rows| %>
    <% est = issue&.estimated_days %>
    <% sch = issue&.schedule_days  %>

    <%# 見積工数 %>
    <% rows.right l(:field_estimated_days), gantt_format_days(est), class: 'estimated-days' %>

    <%# 予定済工数 %>
    <% rows.right l(:field_schedule_days),  gantt_format_days(sch), class: 'schedule-days'  %>
  <% end %>
</div>

app/views/detailed_schedule_gantt/_issue_extra_fields.html.erb
<%#
  Copyright (c) 2025 Structural Line Incorporated
  SPDX-License-Identifier: GPL-2.0-or-later
  https://sl-inc.co.jp
%>

<%# チケットに追加した、見積工数の編集フィールドと予定済工数の値を表示するフィールド %>
<% f = local_assigns[:f] %>

<div class="splitcontent">
  <%# 右寄せにするためにsplitcontentleftを空で作成 %>
	<div class="splitcontentleft"></div>
	<div class="splitcontentright">
    <%# 見積工数 %>
		<p>
      <%= f.label :estimated_days, l(:field_estimated_days) %>
      <%= f.number_field :estimated_days, step: 0.01, min: 0, style: 'width:7em' %>
      <span class="units">人日</span>
		</p>

    <%# 予定済工数 %>
		<p>
		  <%= f.label :schedule_days, l(:field_schedule_days) %>
      <span class="readonly-value"><%= gantt_format_days(issue&.schedule_days) %></span>
      <%= f.hidden_field :schedule_days, value: issue&.schedule_days %>
		</p>
	</div>
</div>

app/views/detailed_schedule_gantt/_project_extra_fields.html.erb
<%#
  Copyright (c) 2025 Structural Line Incorporated
  SPDX-License-Identifier: GPL-2.0-or-later
  https://sl-inc.co.jp
%>

<%#  プロジェクト設定に追加した、開始日と期日と見積工数の編集フィールドと予定済工数の値を表示するフィールド%>

<%# 開始日 %>
<% if @project.safe_attribute? 'project_start_date' %>
  <p><%= f.date_field :project_start_date, :label => l(:field_project_start_date) %></p>
<% end %>

<%# 期日 %>
<% if @project.safe_attribute? 'end_date' %>
  <p><%= f.date_field :end_date, :label => l(:field_project_end_date) %></p>
<% end %>

<%# 見積工数 %>
<% if @project.safe_attribute? 'estimated_days' %>
  <p>
    <%= f.label :estimated_days, l(:field_estimated_days) %>
    <%= f.number_field :estimated_days, step: 0.1, min: 0, style: 'width: 7em'%>
    <span class="info" data-day-label="<%= l(:label_day) %>">
      <%= l(:label_day) %>
    </span>
  </p>
<% end %>

<%# 予定済工数はこの画面では変更できないので表示のみ %>
<p>
  <%= f.label :schedule_days, l(:field_schedule_days) %>
  <%= @project.schedule_days.present? ? gantt_format_days(@project.schedule_days) : l(:label_0day) %>
</p>

app/views/detailed_schedule_gantt/show.html.erb
<!-- 
  Copyright (c) 2025 Structural Line Incorporated
  SPDX-License-Identifier: GPL-2.0-or-later
  https://sl-inc.co.jp
-->

<% @gantt.view = self %>

<h2>
  <%# タイトル %>
  <%= l(:project_module_detailed_schedule_gantt)%>
  
  <div class="contextual new-version">
    <%= link_to '新しいマイルストーンを作成', new_project_version_path(@project), target: '_blank',class: 'icon icon-add' %>
  </div>
  <div class ="contextual" style="margin: 0.5rem;"></div>
  <div class="contextual new-ticket"> <%# スペーシング %>
    <%= link_to '新しいチケットを作成', new_issue_path(project_id: @project.identifier), target: '_blank', class: 'icon icon-add' %>
  </div>
</h2>
<%# フィルタ、オプション、表示する年月、カスタムクエリ を設定するフォーム%>
<%= render partial: 'detailed_schedule_gantt/form' %>

<%= error_messages_for 'query' %>

<% if @query.valid? %>
  <!-- スプレッドシートを描画 -->
  <%= render partial: 'detailed_schedule_gantt/spreadsheet' %>

  <%# ページネーション %>
  <span class="pagination">
    <ul class="pages">
      <%# monthsに指定した数だけ表示する月を戻す %>
      <li class="previous page">
        <%= link_to("\xc2\xab " + l(:label_previous),
                    { params: request.query_parameters.merge(@gantt.params_previous) },
                    accesskey: accesskey(:previous)) %>
      </li>
      <%# monthsに指定した数だけ表示する月を進める %>
      <li class="next page">
        <%= link_to(l(:label_next) + " \xc2\xbb",
                    { params: request.query_parameters.merge(@gantt.params_next) },
                    accesskey: accesskey(:next)) %>
      </li>
    </ul>
    <%# 担当者の1日の工数 表示 / 日表示 ボタン %>
    <button id="toggle-manager-button" type="button">
      <span id="manager-button-status">編集モード</span>
    </button>
  </span>
  <p>
    このスプレッドシートに表示される最大行数は
    <%= @max_rows %>行です。
    <%= link_to "プラグインの設定画面", "/settings/plugin/redmine_detailed_schedule_gantt" %>
    から変更できます。
  </p> 
  <% end %>

<%# サイドバー %>
<% content_for :sidebar do %>
  <%= render partial: 'issues/sidebar' %>
<% end %>

<%# タブに表示するタイトル %>
<% html_title(l(:label_detailed_schedule_gantt)) -%>

<% content_for :header_tags do %>
  <%= render 'detailed_schedule_gantt/header_assets' %>
<% end %>

<%= context_menu %>

app/views/settings/_detailed_schedule_gantt_settings.html.erb
<!-- 
  Copyright (c) 2025 Structural Line Incorporated
  SPDX-License-Identifier: GPL-2.0-or-later
  https://sl-inc.co.jp
-->

<!-- プラグイン設定 -->
<p>
  <%= label_tag 'settings_message', '画面読み込み時に表示する行数' %><br>
  <%= text_field_tag 'settings[initial_rows]', @settings['initial_rows'], size: 6 %>
</p>
  <p>※ 最大行数をオーバーした場合はチケットのIDの大きいものから順に切り捨てられます </p>

<p>
  <%= label_tag 'settings_message', '遅延読み込み時に表示する最大行数' %><br>
  <%= text_field_tag 'settings[max_rows]', @settings['max_rows'], size: 6 %>
</p>
  <p>※ 最大行数をオーバーした場合はチケットのIDの大きいものから順に切り捨てられます </p>